# Generated by Django 5.2.14 on 2026-08-28 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReuniaoAgenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(blank=True, default='', max_length=500)),
                ('titulo', models.TextField(blank=True, default='')),
                ('inicio', models.DateTimeField(blank=True, null=True)),
                ('fim', models.DateTimeField(blank=True, null=True)),
                ('inicio_formatado', models.CharField(blank=True, default='', max_length=50)),
                ('fim_formatado', models.CharField(blank=True, default='', max_length=50)),
                ('data', models.DateField(blank=True, null=True)),
                ('hora_inicio', models.CharField(blank=True, default='', max_length=10)),
                ('hora_fim', models.CharField(blank=True, default='', max_length=10)),
                ('organizador_nome', models.CharField(blank=True, default='', max_length=255)),
                ('organizador_email', models.EmailField(blank=True, default='', max_length=254)),
                ('participantes', models.JSONField(blank=True, default=list)),
                ('link_reuniao', models.TextField(blank=True, default='')),
                ('local', models.TextField(blank=True, default='')),
                ('status', models.CharField(blank=True, default='', max_length=50)),
                ('descricao', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reunioes', to='pedidos.contahostinger')),
            ],
            options={
                'ordering': ['inicio'],
                'constraints': [models.UniqueConstraint(fields=('conta', 'uid'), name='unico_uid_por_conta')],
            },
        ),
    ]
