# Generated by Django 5.2.14 on 2026-10-02 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_reuniaoagenda'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipanteReuniao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('nome', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('ACEITO', 'Aceito'), ('RECUSADO', 'Recusado'), ('TALVEZ', 'Talvez')], default='PENDENTE', max_length=10)),
                ('respondido_em', models.DateTimeField(blank=True, null=True)),
                ('reuniao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas_participantes', to='pedidos.reuniaoagenda')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('reuniao', 'email'), name='unico_participante_por_reuniao')],
            },
        ),
    ]
