# Generated by Django 5.2.14 on 2026-10-02 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_participantereuniao'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantereuniao',
            name='token_resposta',
            field=models.UUIDField(default=None, editable=False, null=True, unique=True),
        ),
    ]
