"""
Django settings for portal project.

Generated by 'django-admin startproject' using Django 5.2.14.
"""

from pathlib import Path
import os
import pymysql
from dotenv import load_dotenv


# ============================================================
# MYSQL DRIVER
# ============================================================

pymysql.install_as_MySQLdb()


# ============================================================
# CAMINHOS
# ============================================================

BASE_DIR = Path(__file__).resolve().parent.parent


# ============================================================
# VARIÁVEIS DE AMBIENTE
# ============================================================

load_dotenv(
    BASE_DIR / "pedidos" / ".env"
)


# ============================================================
# SEGURANÇA
# ============================================================

SECRET_KEY = os.getenv("DJANGO_SECRET_KEY")

if not SECRET_KEY:
    raise RuntimeError(
        "DJANGO_SECRET_KEY não foi configurada."
    )


# PRODUÇÃO
DEBUG = False


ALLOWED_HOSTS = [
    "interno.viesano.com.br",
    "portalinterno-production.up.railway.app",
]


CSRF_TRUSTED_ORIGINS = [
    "https://interno.viesano.com.br",
    "https://portalinterno-production.up.railway.app",
]


# ============================================================
# APLICAÇÕES
# ============================================================

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.humanize",
    "pedidos",
]


# ============================================================
# MIDDLEWARE
# ============================================================

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",

    "whitenoise.middleware.WhiteNoiseMiddleware",

    "django.contrib.sessions.middleware.SessionMiddleware",

    "django.middleware.common.CommonMiddleware",

    "django.middleware.csrf.CsrfViewMiddleware",

    "django.contrib.auth.middleware.AuthenticationMiddleware",

    # ========================================================
    # PROTEÇÃO GLOBAL DE AUTENTICAÇÃO
    # ========================================================

    "django.contrib.messages.middleware.MessageMiddleware",

    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


# ============================================================
# HTTPS / RAILWAY
# ============================================================

SECURE_PROXY_SSL_HEADER = (
    "HTTP_X_FORWARDED_PROTO",
    "https",
)

SECURE_SSL_REDIRECT = True


# ============================================================
# COOKIES DE SEGURANÇA
# ============================================================

SESSION_COOKIE_SECURE = True
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = "Lax"

CSRF_COOKIE_SECURE = True
CSRF_COOKIE_SAMESITE = "Lax"


# ============================================================
# PROTEÇÕES HTTP
# ============================================================

SECURE_CONTENT_TYPE_NOSNIFF = True

SECURE_REFERRER_POLICY = "same-origin"

X_FRAME_OPTIONS = "DENY"


# ============================================================
# HSTS
# ============================================================

SECURE_HSTS_SECONDS = 31536000
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = False


# ============================================================
# CONFIGURAÇÃO DE SESSÃO
# ============================================================

# Sessão expira ao fechar o navegador
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# Sessão dura no máximo 8 horas
SESSION_COOKIE_AGE = 60 * 60 * 8


# ============================================================
# AUTENTICAÇÃO
# ============================================================

LOGIN_URL = "/login/"

LOGIN_REDIRECT_URL = "/"

LOGOUT_REDIRECT_URL = "/login/"


# ============================================================
# URLS
# ============================================================

ROOT_URLCONF = "portal.urls"


# ============================================================
# TEMPLATES
# ============================================================

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",

        "DIRS": [],

        "APP_DIRS": True,

        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]


# ============================================================
# WSGI
# ============================================================

WSGI_APPLICATION = "portal.wsgi.application"


# ============================================================
# BANCO DE DADOS
# ============================================================

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",

        "NAME": os.getenv("DATABASE"),

        "USER": os.getenv("USER"),

        "PASSWORD": os.getenv("PASSWORD"),

        "HOST": os.getenv("HOST"),

        "PORT": os.getenv("DB_PORT", "3306"),

        "OPTIONS": {
            "charset": "utf8mb4",
        },
    }
}


# ============================================================
# VALIDAÇÃO DE SENHA
# ============================================================

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME":
            "django.contrib.auth.password_validation."
            "UserAttributeSimilarityValidator",
    },
    {
        "NAME":
            "django.contrib.auth.password_validation."
            "MinimumLengthValidator",
    },
    {
        "NAME":
            "django.contrib.auth.password_validation."
            "CommonPasswordValidator",
    },
    {
        "NAME":
            "django.contrib.auth.password_validation."
            "NumericPasswordValidator",
    },
]


# ============================================================
# INTERNACIONALIZAÇÃO
# ============================================================

LANGUAGE_CODE = "pt-br"

TIME_ZONE = "America/Sao_Paulo"

USE_I18N = True

USE_TZ = True


# ============================================================
# ARQUIVOS ESTÁTICOS
# ============================================================

STATIC_URL = "static/"

STATIC_ROOT = BASE_DIR / "staticfiles"


STORAGES = {
    "staticfiles": {
        "BACKEND":
            "whitenoise.storage."
            "CompressedManifestStaticFilesStorage",
    },
}


STATICFILES_STORAGE = (
    "whitenoise.storage."
    "CompressedManifestStaticFilesStorage"
)


# ============================================================
# CHAVE PRIMÁRIA
# ============================================================

DEFAULT_AUTO_FIELD = (
    "django.db.models.BigAutoField"
)


# ============================================================
# OMIE
# ============================================================

OMIE_APP_KEY = os.getenv("OMIE_APP_KEY")

OMIE_APP_SECRET = os.getenv("OMIE_APP_SECRET")

OMIE_API_URL_ESTOQUE = (
    "https://app.omie.com.br/api/v1/estoque/consulta/"
)

if not OMIE_APP_KEY:
    raise RuntimeError(
        "OMIE_APP_KEY não foi configurada."
    )

if not OMIE_APP_SECRET:
    raise RuntimeError(
        "OMIE_APP_SECRET não foi configurada."
    )


# ============================================================
# CACHE
# ============================================================

CACHES = {
    "default": {
        "BACKEND":
            "django.core.cache.backends.locmem.LocMemCache",
    }
}


# ============================================================
# E-MAIL
# ============================================================

EMAIL_BACKEND = (
    "django.core.mail.backends.smtp.EmailBackend"
)

EMAIL_HOST = "email-smtp.us-east-1.amazonaws.com"

EMAIL_PORT = 587

EMAIL_USE_TLS = True

EMAIL_USE_SSL = False

EMAIL_TIMEOUT = 30

EMAIL_HOST_USER = os.getenv(
    "EMAIL_HOST_USER"
)

EMAIL_HOST_PASSWORD = os.getenv(
    "EMAIL_HOST_PASSWORD"
)

DEFAULT_FROM_EMAIL = (
    "naoresponda@viesano.com.br"
)